# Generated by Django 5.1.2 on 2025-08-21 16:32

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('comuna_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Comuna',
            },
        ),
        migrations.CreateModel(
            name='DeptoEmpresa',
            fields=[
                ('depto_id', models.AutoField(primary_key=True, serialize=False)),
                ('depto', models.CharField(db_column='depto', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('empresa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('estcivil_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'EstadoCivil',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Region',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('sexo_id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Sexo',
            },
        ),
        migrations.CreateModel(
            name='TipoAusentismo',
            fields=[
                ('tipoausen_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='tipo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLicenciaMedica',
            fields=[
                ('tipoLicenciaMedica_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoLicenciaMedica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cargo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(db_column='cargo', max_length=50)),
                ('depto_id', models.ForeignKey(db_column='depto_id', on_delete=django.db.models.deletion.CASCADE, to='core.deptoempresa')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('personal_id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=8, unique=True)),
                ('dvrut', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
                ('apepat', models.CharField(max_length=50)),
                ('apemat', models.CharField(max_length=50)),
                ('fechanac', models.DateField(blank=True, null=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Estado')),
                ('curriculum', models.FileField(blank=True, null=True, upload_to=core.models.obtener_ruta_documento, verbose_name='Curriculum Vitae')),
                ('certificado_antecedentes', models.FileField(blank=True, null=True, upload_to=core.models.obtener_ruta_documento, verbose_name='Certificado de Antecedentes')),
                ('hoja_vida_conductor', models.FileField(blank=True, null=True, upload_to=core.models.obtener_ruta_documento, verbose_name='Hoja de Vida del Conductor')),
                ('foto_carnet', models.ImageField(blank=True, null=True, upload_to=core.models.obtener_ruta_documento, verbose_name='Foto tipo Carnet')),
                ('certificado_afp', models.FileField(blank=True, null=True, upload_to=core.models.obtener_ruta_documento, verbose_name='Certificado de Afiliación AFP')),
                ('certificado_salud', models.FileField(blank=True, null=True, upload_to=core.models.obtener_ruta_documento, verbose_name='Certificado de Afiliación de Salud')),
                ('certificado_estudios', models.FileField(blank=True, null=True, upload_to=core.models.obtener_ruta_documento, verbose_name='Certificado de Estudios')),
                ('certificado_residencia', models.FileField(blank=True, null=True, upload_to=core.models.obtener_ruta_documento, verbose_name='Certificado de Residencia')),
                ('fotocopia_carnet', models.FileField(blank=True, null=True, upload_to=core.models.obtener_ruta_documento, verbose_name='Fotocopia de Carnet')),
                ('fotocopia_finiquito', models.FileField(blank=True, null=True, upload_to=core.models.obtener_ruta_documento, verbose_name='Fotocopia de Último Finiquito')),
                ('comprobante_banco', models.FileField(blank=True, null=True, upload_to=core.models.obtener_ruta_documento, verbose_name='Formulario de Depósito Bancario')),
                ('comuna_id', models.ForeignKey(blank=True, db_column='comuna_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
                ('estcivil_id', models.ForeignKey(blank=True, db_column='estcivil_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estadocivil')),
                ('region_id', models.ForeignKey(blank=True, db_column='region_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.region')),
                ('sexo_id', models.ForeignKey(blank=True, db_column='sexo_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sexo')),
            ],
            options={
                'db_table': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='InfoLaboral',
            fields=[
                ('infolab_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechacontrata', models.DateField()),
                ('cargo_id', models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.CASCADE, to='core.cargo')),
                ('depto_id', models.ForeignKey(db_column='depto_id', on_delete=django.db.models.deletion.CASCADE, to='core.deptoempresa')),
                ('empresa_id', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('personal_id', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, to='core.personal')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region_id',
            field=models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.CreateModel(
            name='Ausentismo',
            fields=[
                ('ausentismo_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaini', models.DateField()),
                ('fechafin', models.DateField()),
                ('observacion', models.TextField(blank=True, max_length=250, null=True)),
                ('personal_id', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, to='core.personal')),
                ('tipoausen_id', models.ForeignKey(db_column='tipoausen_id', on_delete=django.db.models.deletion.CASCADE, to='core.tipoausentismo')),
            ],
        ),
        migrations.CreateModel(
            name='LicenciaMedicaPorPersonal',
            fields=[
                ('licenciaMedicaPorPersonal_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_folio', models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='N° Folio')),
                ('fechaEmision', models.DateField()),
                ('dias_licencia', models.IntegerField()),
                ('fecha_fin_licencia', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('rutaDoc', models.FileField(upload_to=core.models.obtener_ruta_documento)),
                ('observacion', models.TextField(blank=True, max_length=250, null=True)),
                ('personal_id', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, to='core.personal')),
                ('tipoLicenciaMedica_id', models.ForeignKey(db_column='tipoLicenciaMedica_id', on_delete=django.db.models.deletion.CASCADE, to='core.tipolicenciamedica')),
            ],
        ),
    ]
