# Generated by Django 5.1.2 on 2025-08-21 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faena',
            fields=[
                ('faena_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faena',
                'verbose_name_plural': 'Faenas',
                'db_table': 'Faena',
            },
        ),
        migrations.CreateModel(
            name='TipoTurno',
            fields=[
                ('tipo_turno_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: 7x7, 14x7, 21x7', max_length=50, unique=True)),
                ('dias_trabajo', models.PositiveIntegerField(help_text='Días de trabajo consecutivos')),
                ('dias_descanso', models.PositiveIntegerField(help_text='Días de descanso consecutivos')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Turno',
                'verbose_name_plural': 'Tipos de Turno',
                'db_table': 'TipoTurno',
            },
        ),
        migrations.AddField(
            model_name='infolaboral',
            name='faena_id',
            field=models.ForeignKey(blank=True, db_column='faena_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena'),
        ),
        migrations.AddField(
            model_name='faena',
            name='tipo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipoturno'),
        ),
    ]
