# Generated by Django 5.1.2 on 2025-08-21 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faena_tipoturno_infolaboral_faena_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faena',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de finalización de la faena'),
        ),
        migrations.AddField(
            model_name='faena',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de inicio de la faena'),
        ),
    ]
