# Generated by Django 5.1.2 on 2025-08-21 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faena_fecha_fin_faena_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalFaena',
            fields=[
                ('personal_faena_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(auto_now_add=True, help_text='Fecha cuando se asignó la faena')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio en esta faena')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de finalización en esta faena', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la asignación está activa')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre la asignación', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('faena', models.ForeignKey(db_column='faena_id', on_delete=django.db.models.deletion.CASCADE, to='core.faena')),
                ('personal', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, to='core.personal')),
            ],
            options={
                'verbose_name': 'Asignación de Personal a Faena',
                'verbose_name_plural': 'Asignaciones de Personal a Faena',
                'db_table': 'PersonalFaena',
                'unique_together': {('personal', 'faena', 'fecha_inicio')},
            },
        ),
    ]
