# Generated by Django 5.1.2 on 2025-08-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_personalfaena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalfaena',
            name='fecha_fin',
        ),
        migrations.AddField(
            model_name='personalfaena',
            name='tipo_turno',
            field=models.ForeignKey(blank=True, help_text='Turno específico para esta persona (opcional, usa el de la faena si no se especifica)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipoturno'),
        ),
    ]
