# Generated by Django 5.1.2 on 2025-08-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_personalfaena_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faena',
            name='nombre',
            field=models.CharField(default='SIN ASIGNAR', max_length=150, unique=True),
        ),
    ]
