# Generated by Django 5.1.7 on 2025-08-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_faena_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario que realizó el cambio')),
                ('accion', models.CharField(max_length=50, verbose_name='Tipo de acción')),
                ('tabla_afectada', models.CharField(max_length=50, verbose_name='Tabla o modelo afectado')),
                ('registro_id', models.IntegerField(verbose_name='ID del registro afectado')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos antes del cambio')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos después del cambio')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del cambio')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('descripcion', models.TextField(verbose_name='Descripción del cambio')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'AuditLog',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
