# Generated by Django 5.1.7 on 2025-08-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='detalles_adicionales',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='datos_anteriores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='datos_nuevos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='registro_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='tabla_afectada',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
